### ISSUE TITLE
TODO App'e çevirelim lütfen

### ISSUE THREAD

**Issue by barisener** [KaygusuzBK/Flask#3]
**Proje boş kalmasın, TODO App'e çevirelim lütfen!**

**Comment by KaygusuzBK** [comment]
![image](https://user-images.githubusercontent.com/74183528/212491516-f826ab84-11dd-4893-8425-2b38d1f7d3b3.png)

olur gibi

**Comment by barisener** [comment]
PR'ı da chatGPT'ye açarsın o zaman

**Comment by KaygusuzBK** [comment]
Sizi birazda olsa tatmin edebildiysek ne mutlu bize @barisener

**Comment by barisener** [comment]
Deploy edilse de kullansak uygulamayı
